<a href="https://colab.research.google.com/github/parth025sharma/ML/blob/master/Data_engg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
#reading csv file from url
df=pd.read_csv('http://13.234.66.67/summer19/datasets/info.csv')

In [57]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [58]:
#taking values without header like age purchase etc
x=df.iloc[:,0:].values#df.iloc is index location of df
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [59]:
#removing missing value and replacing missing value with some relevant data
from sklearn.preprocessing import Imputer
# axis gives us the row or column if axis is 0 then it us column applied else row applied
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')#Stratigy replacis the value which is given or putted in place of NaN here it is "mean" value
impute=imp.fit(x[:,1:3]) #this is fitting of columns that we want to process

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
#time for transporting fitted coumns
#fit gives the schema and transform changes the value
x[:,1:3]=impute.transform(x[:,1:3])

In [0]:
#string label int / float
from sklearn.preprocessing import LabelEncoder
cont=LabelEncoder()# this is from country labeling

In [62]:
#now applying column first in labelEn
x[:,0]=cont.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [63]:
#labeliing last column
p=LabelEncoder()
x[:,3]=p.fit_transform(x[:,3])
x

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [64]:
#now enoding first column -----making subcolumn of first column
from sklearn.preprocessing import OneHotEncoder
firstcl=OneHotEncoder(categorical_features=[0]) #defining exact column number where we want to make catagory
x=firstcl.fit_transform(x).toarray()#.toarray is type conversion from matrix to array 
#after transormation we need to convert into numpy array

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [65]:
x.astype(int) #to show in int only

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])

OneHotEncoder

Imputer

LabelEncoder
